### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [kennedy69/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by kennedy69** [comment]
![1111122](https://user-images.githubusercontent.com/52185202/68477200-65208480-025f-11ea-9914-033dfb2807cd.png)

**Comment by unixorn** [comment]
Thanks!

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/821
